name: Java CI

on: [push]

jobs:
  jobs1:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  jobs2:
      name: copy files using scp
      runs-on: ubuntu-latest
      steps:
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "/home/zombie/thingsboard/application/target/thingsboard.deb"
          target: "/home/rabi"